### ISSUE TITLE
Pre-processing ATLAS v2 data

### ISSUE THREAD

**Issue by fragalassi** [npnl/StrokePreprocessingPipeline#1]
Dear authors,

Thank you very much for sharing the ATLAS data. 

I would like to ask whether this repository corresponds the reference pipeline for the pre-processed ATLAS v2 data that has been released. That is: registration to MNI, etc...as mentioned in your paper on ATLAS.

Best regards,
Francesca

**Comment by leiliew** [comment]
Yes - the repository found here (https://fcon_1000.projects.nitrc.org/indi/retro/atlas.html) contains data that has been preprocessed as specified in our paper here (https://www.nature.com/articles/s41597-022-01401-7), in that it is registered to MNI space, de-faced, etc.
